name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        # IF your app is inside a subfolder, uncomment the line below and change 'YOUR_FOLDER_NAME'
        # working-directory: YOUR_FOLDER_NAME
        run: flutter pub get

      - name: CocoaPods update
        # IF your app is inside a subfolder, update the path below (e.g., YOUR_FOLDER_NAME/ios)
        working-directory: ios
        run: pod repo update

      - name: Build iOS App
        # IF your app is inside a subfolder, uncomment the line below and change 'YOUR_FOLDER_NAME'
        # working-directory: YOUR_FOLDER_NAME
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        # IF your app is inside a subfolder, update the path below (e.g., YOUR_FOLDER_NAME/build/ios/iphoneos)
        working-directory: build/ios/iphoneos
        run: |
          mkdir Payload
          mv Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # IF your app is inside a subfolder, update the path below (e.g., YOUR_FOLDER_NAME/build/ios/iphoneos/FlutterIpaExport.ipa)
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
